### PR TITLE
Issue #48 : Migrated to Java 11

### LINKED ISSUE #48: Migrate to java 11
Main goal is to remove `okhttp3` dependency

### PR DESCRIPTION
**Pull request by suratdas**
Fixes #48

### CODE REVIEW

**Comment by suratdas** [comment]
Tested locally and works fine with the java-examples I pushed earlier. Also, all unit tests are passing. The check complains because it set up java 8 to run but it will run with java 11. Also, my IntelliJ auto formatted some imports and indentations.
BTW, are we mandating our consumers to use Java 11 to be able to use this repo ?

**Comment by pashidlos** [comment]
@suratdas thanks for contribution!

only now I realised it's not gonna be compatible with java 8 :)
you could change `.github/workflows/gradle.yml` with Java version 11 and it should work

np, I'll make it major version `5.0.0`

**Comment by pashidlos** [comment]
not sure why but jitpack is not building new version `5.0.0-SNAPSHOT`
https://jitpack.io/com/github/Visual-Regression-Tracker/sdk-java/5.0.0-SNAPSHOT/build.log

**Comment by suratdas** [comment]
> not sure why but jitpack is not building new version `5.0.0-SNAPSHOT`
> seems somewhere we need to setup java 11 for it
> https://jitpack.io/com/github/Visual-Regression-Tracker/sdk-java/5.0.0-SNAPSHOT/build.log

Looks like we need jitpack.yml file per the comment at https://github.com/jitpack/jitpack.io/issues/2567#issuecomment-589490483

**Comment by suratdas** [comment]
@pashidlos Did you figure out the jitpack build issue for Java 11 ? Sorry, I never worked with jitpack. So, cannot help immediately.

**Comment by pashidlos** [comment]
@suratdas me neither ) 
I guess you could create this file and let's check if it works

**Comment by pashidlos** [comment]
LGTM!
@suratdas  thanks for contribution!

**Pull request merged**
